name: carbon_aware_sdk
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  http: '>=0.13.0 <0.14.0'
  intl: '^0.17.0'
  meta: '^1.1.8'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
